name: IBM Cloud Auto Restart

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 12 * * FRI'

jobs:
  ibm-cloud-restart:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Init
      run: |
        chmod -R 777 ./IBM_Cloud_CLI/
    - name: IBM Cloud CF Restart1
      env:
        IBM_ACCOUNT_USER1: ${{ secrets.IBM_ACCOUNT_USER1 }}
        IBM_ACCOUNT_PASS1: ${{ secrets.IBM_ACCOUNT_PASS1 }}
        RESOURSE_ID1: ${{ secrets.RESOURSE_ID1 }}
        IBM_APP_NAME1: ${{ secrets.IBM_APP_NAME1 }}
      run: |
        ./IBM_Cloud_CLI/ibmcloud login -u $IBM_ACCOUNT_USER1 -p $IBM_ACCOUNT_PASS1 -r us-south -g $RESOURSE_ID1 2>/dev/null
        ./IBM_Cloud_CLI/ibmcloud target --cf
        ./IBM_Cloud_CLI/ibmcloud cf install -v 6.5.1 -f
        ./IBM_Cloud_CLI/ibmcloud cf restart "$IBM_APP_NAME1"
        ./IBM_Cloud_CLI/ibmcloud logout ;
    - name: IBM Cloud CF Restart2
      env:
        IBM_ACCOUNT_USER2: ${{ secrets.IBM_ACCOUNT_USER2 }}
        IBM_ACCOUNT_PASS2: ${{ secrets.IBM_ACCOUNT_PASS2 }}
        RESOURSE_ID2: ${{ secrets.RESOURSE_ID2 }}
        IBM_APP_NAME2: ${{ secrets.IBM_APP_NAME2 }}
      run: |
        ./IBM_Cloud_CLI/ibmcloud login -u $IBM_ACCOUNT_USER2 -p $IBM_ACCOUNT_PASS2 -r us-south -g $RESOURSE_ID2 2>/dev/null
        ./IBM_Cloud_CLI/ibmcloud target --cf
        ./IBM_Cloud_CLI/ibmcloud cf restart "$IBM_APP_NAME2"
        ./IBM_Cloud_CLI/ibmcloud logout ;
        
    
